### ISSUE TITLE
won't get to work with gulp-rework

### ISSUE THREAD

**Issue by vedam** [jacoblane/rework-expand#1]
Hey,
first of all, thanx for this nice one. Seems to be exactly what I was searching for. Unfortunately I'm not able to get it working. 

I'm using rework via gulp-rework and even your base example:

```
:expand {
  expand-selector: .w25, .w50, .w75, .w100;
  expand-width: 25%, 50%, 75%, 100%
}
```

seems to not get parsed. outputs:

```
:expand {
  expand-selector: .w\:25, .w\:50, .w\:75, .w\:100;
  expand-width: 25%, 50%, 75%, 100%;
}
```

any idea appreciated

**Comment by jacoblane** [comment]
My guess is that you need to actually call the `expand` function when you pass it to gulp-rework, as it is a closure. The following very basic gulpfile worked fine for me, with an input.css file containing the example you cite:

```
// Require dependencies.
var gulp       = require('gulp');
var rework     = require('gulp-rework');
var rename     = require('gulp-rename');
var expand     = require('rework-expand');


gulp.task('css-build', function () {
  gulp.src('./input.css')
    .pipe(rework(
      expand() // actually call the function here
    ))
    .pipe(rename('./output.css'))
    .pipe(gulp.dest('./'))
    ;
});

gulp.task('default', ['css-build']);
```

Perhaps if you share the relevant portion of your gulpfile I can be of more help.

**Comment by vedam** [comment]
thx for your fast answer.
I'm working with streams in gulp so that there are passed multiple files from src-folder:

```
const gulp        = require('gulp')
const babel       = require('gulp-babel')
const sourcemaps  = require('gulp-sourcemaps')
const rework      = require('gulp-rework')
const expand      = require('rework-expand')
const browsersync = require('browser-sync')

gulp.task('css', () => {

  return gulp.src([
    './src/*.css',
    '!./src/_*.css', // exlude partials
  ])

  //  pipe to rework with plugins
  .pipe(rework(
    // ...require other plugins...blabla...
     expand,
    { sourcemap: false }
  ))

  .pipe(gulp.dest('./build/css'))
  .pipe(browsersync.stream());

})

gulp.task('default', ['css']);

```

**Comment by vedam** [comment]
Got it working if I don't return gulp.src:

```
const gulp        = require('gulp')
const babel       = require('gulp-babel')
const sourcemaps  = require('gulp-sourcemaps')
const rework      = require('gulp-rework')
const expand      = require('rework-expand')
const browsersync = require('browser-sync')

gulp.task('css', () => {
  gulp.src([ './src/*.css' ])
  .pipe(rework( expand(), { sourcemap: false } ))
  .pipe(gulp.dest('./'))
  .pipe(browsersync.stream())
  ;
})

gulp.task('default', ['css']);


```

Now I'll have to check if any of all other tasks depend on returning gulp.src.
Thx for your help.

**Comment by jacoblane** [comment]
I don't think the issue is with `gulp.src`.  In your first example you pass `expand` to the `rework` function. Instead you should pass `expand()`, which you do in the second example.  I quickly replicated your file, though without using babel, and if you use `expand()` it works while still returning `gulp.src`.
